#开发环境
#db:
#  hostmysql: 123.60.129.35
#  pw: 2004
#  hostredis: 123.60.129.35
#开发环境
db:
  hostmysql: 127.0.0.1
  pw: 2004
  hostredis: 127.0.0.1
#path:
#  lujin: /home/cxkbalq/file/lujing/
#  temp:  /home/cxkbalq/file/temp/
#  file: /home/cxkbalq/file/file

#path:
#  lujin: C:\Downloads\temp\image\
#  temp: C:\Downloads\temp\
#  file: C:\Downloads\file\
#  croveImage: C:\Downloads\file\croveImage\
path:
  lujin: D:\Downloads\temp\image\
  temp: D:\Downloads\temp\
  file: D:\Downloads\file\
  croveImage: D:\Downloads\file\croveImage\